### PR TITLE
TypeScript conversion

### PR DESCRIPTION
**Pull request by codynova**
Convert everything to TypeScript. This is almost ready to be merged for initial testing. Please review to the best of your ability as the updates are extensive...

To do:

- [x] collision/AABB
- [x] collision/ArrayCollisionMatrix
- [x] collision/Broadphase
- [x] collision/GridBroadphase
- [x] collision/NaiveBroadphase
- [x] collision/ObjectCollisionMatrix
- [x] collision/OverlapKeeper
- [x] collision/Ray
- [x] collision/RaycastResult
- [x] collision/SAPBroadphase
- [x] constraints/ConeTwistConstraint
- [x] constraints/Constraint
- [x] constraints/DistanceConstraint
- [x] constraints/HingeConstraint
- [x] constraints/LockConstraint
- [x] constraints/PointToPointConstraint
- [x] equations/ConeEquation
- [x] equations/ContactEquation
- [x] equations/Equation
- [x] equations/FrictionEquation
- [x] equations/RotationalEquation
- [x] equations/RotiationalMotorEquation
- [x] material/ContactMaterial
- [x] material/Material
- [x] math/JacobianElement
- [x] math/Mat3
- [x] math/Quaternion
- [x] math/Transform
- [x] math/Vec3
- [x] objects/Body
- [x] objects/RaycastVehicle
- [x] objects/RigidVehicle
- [x] objects/SPHSystem
- [x] objects/Spring
- [x] objects/WheelInfo
- [x] shapes/Box
- [x] shapes/ConvexPolyhedron
- [x] shapes/Cylinder
- [x] shapes/Heightfield
- [x] shapes/Particle
- [x] shapes/Plane
- [x] shapes/Shape
- [x] shapes/Sphere
- [x] shapes/Trimesh
- [x] solver/GSSolver
- [x] solver/Solver
- [x] solver/SplitSolver 
- [x] utils/EventTarget
- [x] utils/Octree
- [x] utils/Pool
- [x] utils/TupleDictionary
- [x] utils/Utils
- [x] utils/Vec3Pool
- [x] world/Narrowphase
- [x] world/World

### CODE REVIEW

**Comment by codynova** [comment]
Once this is done we should investigate improvements that were explored in the [dapao fork](https://github.com/TheRohans/dapao/issues?q=is%3Aissue)

**Comment by codynova** [comment]
I should be able to wrap this up tomorrow

**Comment by codynova** [comment]
To do:

- [ ] objects/Body
- [ ] objects/RaycastVehicle
- [ ] shapes/ConvexPolyhedron
- [ ] shapes/Heightfield
- [ ] shapes/Trimesh
- [ ] world/Narrowphase
- [ ] world/World

**Comment by stockHuman** [comment]
This is stellar :)

**Comment by codynova** [comment]
Interestingly it appears that `Narrowphase` had a bug in `createFrictionFromAverage` which caused this condition to always evaluate to false:

```

if (c.bodyA !== bodyA) {
  averageNormal.vadd(c.ni, averageNormal)
  averageContactPointA.vadd(c.ri, averageContactPointA)
  averageContactPointB.vadd(c.rj, averageContactPointB)
} else {
  averageNormal.vsub(c.ni, averageNormal)
  averageContactPointA.vadd(c.rj, averageContactPointA)
  averageContactPointB.vadd(c.ri, averageContactPointB)
}
```

**Comment by codynova** [comment]
There was a similar error in `GridBroadphase.prototype.addBoxToBins`:

```js
  const bi = bodies[i]
  const si = bi.shape
```

Where a `Body` does not have the property `shape`

**Comment by codynova** [comment]
Merged and released in `cannon-es@0.8.0`

**Pull request merged**
