### PR TITLE
Add TS build config, convert src/math/ and src/utils/ to TS

### PR DESCRIPTION
**Pull request by codynova**

### CODE REVIEW

**Comment by codynova** [comment]
Tested with the most recent version of `use-cannon`

**Comment by drcmda** [comment]
nice! merge whenever you think it's ready

**Comment by codynova** [comment]
This should be stable. I'm merging now so that we can use in the next version of `use-cannon` and make sure there are no bugs. There should be no functional changes, only type updates.

**Comment by drcmda** [comment]
are you "codynova" on npm? if yes you have npm publish right now. if no please tell me, or else i've given it to a complete stranger :-P

**Comment by codynova** [comment]
Hahaha yes, that's me. 😄 I'll go ahead and release a new version `0.7.0` so we can update `use-cannon` and get people testing the TypeScript version

**Comment by codynova** [comment]
Just waiting on npm cache to clear so my permissions are valid 👍

**Comment by codynova** [comment]
Released cannon-es@0.7.0

**Pull request merged**
