### PR TITLE
Add TS config to build, convert Vec3 to TS

### PR DESCRIPTION
**Pull request by codynova**
@drcmda How do you feel about this? I'd love to convert Cannon to TypeScript to improve the developer experience for both Cannon and use-cannon.

If we were to convert to TypeScript, would you want to keep the JSDoc comments?

I don't have experience with rollup + TypeScript. Using the build process in this PR I get an error on the TypeScript file:

```
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src\math\Vec3.ts (20:16)
20:   static ZERO = new Vec3(0, 0, 0);
```

Any idea what I'm doing wrong?

### CODE REVIEW

**Comment by codynova** [comment]
Closing because this isn't ready to merge, I just wanted to open a discussion

**Comment by drcmda** [comment]
i dont know enough about typescript but did you see this: https://github.com/TheRohans/dapao ?

**Comment by codynova** [comment]
Yep, I tried the `dapao` port of Cannon in the past, and it works well enough - but it seems to have been abandoned some time ago, and the TypeScript conversion is pretty minimal, not to mention there are still several bugs lingering from the original Cannon library - some of which have been fixed in cannon-es.

Is converting cannon-es to TypeScript something you'd be okay with, or would you rather leave it as-is? I wouldn't mind forking if necessary

**Comment by drcmda** [comment]
sure, go ahead, types would be great

**Pull request closed without merging**
